build:
  image: haskell
  commands:
    - cabal update
    - cabal sandbox init
    - cabal install
    - cabal configure
    - cabal test
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: omelhoro1/haskell-hutton
